
name: Doxygen Action

on:
  push:
    branches:
      - main  # Modify to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Doxygen
      run: |
        sudo apt-get update -y
        sudo apt-get install -y doxygen doxygen-latex

    - name: Generate Doxygen Documentation
      run: |
        doxygen Doxyfile  # Modify this line to match your Doxyfile location

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html  # Modify this line to match your Doxygen output directory
